export const TABLE_SCHEMAS = {
  upload_batches: `
    CREATE TABLE IF NOT EXISTS upload_batches (
      batch_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      file_name TEXT NOT NULL,
      uploaded_at TEXT NOT NULL,
      source_row_count INTEGER,
      rows_imported INTEGER,
      rows_rejected INTEGER
    );
  `,
  import_rejected_rows: `
    CREATE TABLE IF NOT EXISTS import_rejected_rows (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      batch_id INTEGER NOT NULL,
      reject_reason TEXT NOT NULL,
      raw_row TEXT NOT NULL,
      FOREIGN KEY (batch_id) REFERENCES upload_batches(batch_id)
    );
  `,
  financial_years: `
    CREATE TABLE IF NOT EXISTS financial_years (
      fy_code TEXT PRIMARY KEY,
      fy_name TEXT NOT NULL
    );
  `,
  billing_types: `
    CREATE TABLE IF NOT EXISTS billing_types (
      billing_type TEXT PRIMARY KEY,
      billing_desc TEXT NOT NULL,
      classification TEXT NOT NULL
    );
  `,
  materials: `
    CREATE TABLE IF NOT EXISTS materials (
      material_code TEXT PRIMARY KEY,
      material_desc TEXT NOT NULL,
      division TEXT NOT NULL,
      crop TEXT NOT NULL,
      variety TEXT NOT NULL,
      sales_unit TEXT NOT NULL,
      own_trade TEXT NOT NULL
    );
  `,
  employees: `
    CREATE TABLE IF NOT EXISTS employees (
      employee_id TEXT PRIMARY KEY,
      employee_name TEXT NOT NULL,
      role TEXT NOT NULL
    );
  `,
  customers: `
    CREATE TABLE IF NOT EXISTS customers (
      customer_id TEXT PRIMARY KEY,
      customer_name TEXT NOT NULL,
      dist_channel TEXT NOT NULL
    );
  `,
  territories: `
    CREATE TABLE IF NOT EXISTS territories (
      territory_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      state TEXT NOT NULL,
      territory TEXT NOT NULL,
      territory_incharge_id TEXT,
      am_id TEXT,
      rbm_id TEXT,
      dbm_id TEXT,
      FOREIGN KEY (territory_incharge_id) REFERENCES employees(employee_id),
      FOREIGN KEY (am_id) REFERENCES employees(employee_id),
      FOREIGN KEY (rbm_id) REFERENCES employees(employee_id),
      FOREIGN KEY (dbm_id) REFERENCES employees(employee_id),
      UNIQUE (state, territory)
    );
  `,
  sales_data: `
    CREATE TABLE IF NOT EXISTS sales_data (
      invoice_id TEXT PRIMARY KEY,
      invoice_date DATE NOT NULL,
      billing_type TEXT NOT NULL,
      customer_id TEXT NOT NULL,
      material_code TEXT NOT NULL,
      territory_id INTEGER NOT NULL,
      qty INTEGER NOT NULL,
      sales_unit TEXT NOT NULL,
      sales_amount_inr NUMERIC(15, 2) NOT NULL,
      cogm NUMERIC(15, 2) NOT NULL,
      season_code TEXT NOT NULL,
      fy_code TEXT NOT NULL,
      batch_id INTEGER,
      FOREIGN KEY (billing_type) REFERENCES billing_types(billing_type),
      FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
      FOREIGN KEY (material_code) REFERENCES materials(material_code),
      FOREIGN KEY (territory_id) REFERENCES territories(territory_id),
      FOREIGN KEY (fy_code) REFERENCES financial_years(fy_code),
      FOREIGN KEY (batch_id) REFERENCES upload_batches(batch_id)
    );
  `,
  ai_query_log: `
    CREATE TABLE IF NOT EXISTS ai_query_log (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      question TEXT NOT NULL,
      session_id TEXT,
      sql_query TEXT,
      was_limitation_shown BOOLEAN,
      timestamp TEXT NOT NULL
    );
  `
};
