export const TABLE_SCHEMAS = {
  upload_batches: `
    CREATE TABLE IF NOT EXISTS upload_batches (
      batch_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      file_name TEXT NOT NULL,
      uploaded_at TEXT NOT NULL,
      source_row_count INTEGER,
      rows_imported INTEGER,
      rows_rejected INTEGER,
      file_hash TEXT UNIQUE,
      is_active BOOLEAN DEFAULT TRUE,
      fy_code TEXT,
      min_date DATE,
      max_date DATE,
      record_count INTEGER,
      deleted_at TIMESTAMPTZ,
      schema_columns JSONB
    );
  `,
  import_rejected_rows: `
    CREATE TABLE IF NOT EXISTS import_rejected_rows (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      batch_id INTEGER NOT NULL,
      reject_reason TEXT NOT NULL,
      raw_row TEXT NOT NULL,
      FOREIGN KEY (batch_id) REFERENCES upload_batches(batch_id)
    );
  `,
  financial_years: `
    CREATE TABLE IF NOT EXISTS financial_years (
      fy_code TEXT PRIMARY KEY,
      fy_name TEXT NOT NULL
    );
  `,
  billing_types: `
    CREATE TABLE IF NOT EXISTS billing_types (
      billing_type TEXT PRIMARY KEY,
      billing_desc TEXT NOT NULL,
      classification TEXT NOT NULL
    );
  `,
  materials: `
    CREATE TABLE IF NOT EXISTS materials (
      material_code TEXT PRIMARY KEY,
      material_desc TEXT NOT NULL,
      division TEXT NOT NULL,
      crop TEXT NOT NULL,
      variety TEXT NOT NULL,
      sales_unit TEXT NOT NULL,
      own_trade TEXT NOT NULL
    );
  `,
  employees: `
    CREATE TABLE IF NOT EXISTS employees (
      employee_id TEXT PRIMARY KEY,
      employee_name TEXT NOT NULL,
      role TEXT NOT NULL
    );
  `,
  customers: `
    CREATE TABLE IF NOT EXISTS customers (
      customer_id TEXT PRIMARY KEY,
      customer_name TEXT NOT NULL,
      dist_channel TEXT NOT NULL
    );
  `,
  territories: `
    CREATE TABLE IF NOT EXISTS territories (
      territory_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      state TEXT NOT NULL,
      territory TEXT NOT NULL,
      territory_incharge_id TEXT,
      am_id TEXT,
      rbm_id TEXT,
      dbm_id TEXT,
      FOREIGN KEY (territory_incharge_id) REFERENCES employees(employee_id),
      FOREIGN KEY (am_id) REFERENCES employees(employee_id),
      FOREIGN KEY (rbm_id) REFERENCES employees(employee_id),
      FOREIGN KEY (dbm_id) REFERENCES employees(employee_id),
      UNIQUE (state, territory)
    );
  `,
  sales_data_raw: `
    CREATE TABLE IF NOT EXISTS sales_data_raw (
      id BIGSERIAL PRIMARY KEY,
      batch_id INTEGER NOT NULL,
      invoice_id TEXT NOT NULL,
      invoice_date DATE NOT NULL,
      billing_type TEXT NOT NULL,
      customer_id TEXT NOT NULL,
      material_code TEXT NOT NULL,
      territory_id INTEGER NOT NULL,
      qty NUMERIC(15, 4) NOT NULL,
      sales_unit TEXT NOT NULL,
      sales_amount_inr NUMERIC(15, 2) NOT NULL,
      cogm NUMERIC(15, 2) NOT NULL,
      season_code TEXT NOT NULL,
      fy_code TEXT NOT NULL,

      -- Additional document details
      billing_type_desc TEXT,
      division TEXT,
      distribution_channel TEXT,
      state TEXT,
      plant TEXT,
      storage_location TEXT,
      sales_order_no TEXT,
      customer_reference TEXT,
      indent_no TEXT,
      ipt_sr_request_no TEXT,
      ipt_sr_request_date DATE,
      accounting_doc_no TEXT,
      fiscal_year INTEGER,
      customer_no TEXT,
      customer_name TEXT,
      line_item_no TEXT,
      crop_name TEXT,
      variety_name TEXT,
      own_trade TEXT,
      material_name TEXT,
      batch_no TEXT,
      expiry_date DATE,
      currency TEXT,
      sales_price NUMERIC(15,2),
      sales_amount NUMERIC(15,2),
      exchange_rate NUMERIC(15,4),
      base_currency_inr TEXT,
      sales_price_inr NUMERIC(15,2),
      
      -- Hierarchy & Employee metadata
      territory_name TEXT,
      ti_id TEXT,
      ti_name TEXT,
      am_id TEXT,
      am_name TEXT,
      rbm_id TEXT,
      rbm_name TEXT,
      dbm_id TEXT,
      dbm_name TEXT,
      
      created_by TEXT,
      created_at TIMESTAMP DEFAULT NOW(),

      FOREIGN KEY (billing_type) REFERENCES billing_types(billing_type),
      FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
      FOREIGN KEY (material_code) REFERENCES materials(material_code),
      FOREIGN KEY (territory_id) REFERENCES territories(territory_id),
      FOREIGN KEY (fy_code) REFERENCES financial_years(fy_code),
      FOREIGN KEY (batch_id) REFERENCES upload_batches(batch_id)
    );
  `,
  ai_query_log: `
    CREATE TABLE IF NOT EXISTS ai_query_log (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      question TEXT NOT NULL,
      session_id TEXT,
      sql_query TEXT,
      was_limitation_shown BOOLEAN,
      timestamp TEXT NOT NULL
    );
  `,
  copilot_sessions: `
    CREATE TABLE IF NOT EXISTS copilot_sessions (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      user_id VARCHAR(255) NULL,
      title VARCHAR(255),
      status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'archived')),
      context JSONB NOT NULL DEFAULT '{}',
      summary TEXT,
      total_messages INTEGER NOT NULL DEFAULT 0,
      started_at TIMESTAMP NOT NULL DEFAULT NOW(),
      last_activity_at TIMESTAMP NOT NULL DEFAULT NOW(),
      created_at TIMESTAMP NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMP NOT NULL DEFAULT NOW()
    );
  `,
  copilot_messages: `
    CREATE TABLE IF NOT EXISTS copilot_messages (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      session_id UUID NOT NULL REFERENCES copilot_sessions(id) ON DELETE CASCADE,
      role VARCHAR(20) NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
      content TEXT NOT NULL,
      metadata JSONB DEFAULT '{}',
      created_at TIMESTAMP NOT NULL DEFAULT NOW()
    );
  `,
  copilot_executions: `
    CREATE TABLE IF NOT EXISTS copilot_executions (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      session_id UUID NOT NULL REFERENCES copilot_sessions(id) ON DELETE CASCADE,
      message_id UUID REFERENCES copilot_messages(id) ON DELETE SET NULL,
      intent VARCHAR(100),
      query_plan JSONB,
      filters JSONB,
      result_summary TEXT,
      execution_status VARCHAR(20) DEFAULT 'success' CHECK (execution_status IN ('success', 'failed')),
      execution_time_ms INTEGER,
      created_at TIMESTAMP NOT NULL DEFAULT NOW()
    );
  `,
  dataset_aggregates: `
    CREATE TABLE IF NOT EXISTS dataset_aggregates (
      id SERIAL PRIMARY KEY,
      batch_id INTEGER NOT NULL,
      fy_code TEXT NOT NULL,
      dimension_type TEXT NOT NULL,
      dimension_value TEXT,
      gross_sales NUMERIC DEFAULT 0,
      returns_value NUMERIC DEFAULT 0,
      cancelled_value NUMERIC DEFAULT 0,
      net_external_sales NUMERIC DEFAULT 0,
      total_cogm NUMERIC DEFAULT 0,
      transaction_count INTEGER DEFAULT 0,
      computed_at TIMESTAMP DEFAULT NOW(),
      UNIQUE (batch_id, dimension_type, dimension_value),
      FOREIGN KEY (batch_id) REFERENCES upload_batches(batch_id) ON DELETE CASCADE
    );
  `
};
